wazuh_repo:
  keyring_path: '/usr/share/keyrings/wazuh.gpg'
  apt: 'deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages-dev.wazuh.com/staging/apt/ unstable main'
  yum: 'https://packages-dev.wazuh.com/staging/yum/'
  gpg: 'https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH'
  path: '/tmp/WAZUH-GPG-KEY'

certs_gen_tool_version: "5.0"

# Url of certificates generator tool
certs_gen_tool_url: "https://packages-dev.wazuh.com/{{ certs_gen_tool_version }}/wazuh-certs-tool.sh"
